# api/routes/__init__.py
"""Kanisa Langu API Routes."""
from .auth import router as auth_router
from .references import router as references_router
from .hierarchy import router as hierarchy_router
from .admins import router as admins_router
from .members import router as members_router
from .finance import router as finance_router
from .envelope import router as envelope_router
from .harambee import router as harambee_router
from .sunday_service import router as sunday_service_router
from .attendance import router as attendance_router
from .meetings import router as meetings_router
from .assets import router as assets_router
from .payments import router as payments_router
from .reports import router as reports_router

all_routers = [
    auth_router,             # /auth/...
    references_router,       # /references/...
    hierarchy_router,        # /dioceses, /provinces, /head-parishes, etc.
    admins_router,           # /admins/...
    members_router,          # /members/...
    finance_router,          # /finance/...
    envelope_router,         # /envelope/...
    harambee_router,         # /harambee/...
    sunday_service_router,   # /sunday-services/...
    attendance_router,       # /attendance/...
    meetings_router,         # /meetings/...
    assets_router,           # /assets/...
    payments_router,         # /payments/...
    reports_router,          # /reports/...
]
